### ISSUE TITLE
Add Event.list()

### ISSUE THREAD

**Issue by muga** [intercom/intercom-java#116]
My application uses intercom-java 2.1.0 to access Intercom API and fetch (list) objects like Users, User Events, etc. For fetching User objects, we could use and call `User.list` method. But I noticed that Event doesn't have such method like `list()`. 

If you could add such Event.list method to fetch Events, it would be great for me. Or do you have any reasons why you cannot add `list` method to Event class? Or please let me know if you have any good ideas workarounds to fetch Events.
## Version info
- intercom-java version: 2.1.0
- Java version: 1.7

**Comment by choran** [comment]
Hi @muga,
We were just following up on some older issues and I noticed we never responded on this. Apologies for this and we are trying to make sure we try and get back to issue more quickly in future. 
Yes, at the moment there is no listing of events. Events are slightly different from users in that from the API you cannot just list all the event in an app, you can list all the[ events per customer ](https://developers.intercom.com/reference#list-user-events ) however. Alternatively, you can get a summary of events rather than each individual event. These would be possible ways we could add some form of listing here.
Thanks
Cathal

**Comment by muga** [comment]
@choran Thank you for explaining. My application started using a REST client library to access Intercom API directly so, the functionality is not required by my application.

I close this ticket.
