### ISSUE TITLE
Conversation Ratings

### ISSUE THREAD

**Issue by brandonfuller** [intercom/intercom-java#155]
I already asked for this via Intercom on Intercom but you get no love there.  Just a template message saying "we logged the enhancement".

When you add features, it would be swell if they were API first or simultaneous.   It helps with adoption.

**Comment by thewheat** [comment]
Hi @brandonfuller, totally agree with trying to get the API inline with the newest features: we're working on some processes this quarter to try get things on the right trajectory for our SDKs

Taking a look at this, it seems that the conversation ratings are not fully readable via the [API](https://developers.intercom.io/reference) yet
- When a rating is made there is a `conversation_rating_changed` conversation part but there is no details into what the rating is.
```
{
	"type": "conversation_part",
	"id": "891856456",
	"part_type": "conversation_rating_changed",
	"body": null,
	"created_at": 1509445814,
	"updated_at": 1509445814,
	"notified_at": 1509445814,
	"assigned_to": null,
	"author": {
		"type": "bot",
		"id": "767906"
	},
	"attachments": [],
	"external_id": null
}
```
- Similar case when a text remark is specified there is a `conversation_rating_remark_added` conversation part but no details of the contents
```
{
	"type": "conversation_part",
	"id": "891840788",
	"part_type": "conversation_rating_remark_added",
	"body": null,
	"created_at": 1509445411,
	"updated_at": 1509445411,
	"notified_at": 1509445411,
	"assigned_to": null,
	"author": {
		"type": "bot",
		"id": "767906"
	},
	"attachments": [],
	"external_id": null
}
```

So we're currently blocked due to the **API not providing sufficient details**. As there is no development work currently possible in the SDK itself, I'm going to close this issue. 

If the API does support extracting the ratings, feel free to reopen and we can get to implement it 👍
