### ISSUE TITLE
Company.getSessionCount() returning '0' in Java SDK

### ISSUE THREAD

**Issue by mattdonnelly** [intercom/intercom-java#202]
#### Description

A user reported that when making a fetching a company, the company session count  is 0 even when company has had multiple sessions. Company object is being returned correctly but the session count parsing doesn't seem to be working.

* * *

#### Evidence

User's code:
```
Company company = Company.find(of("company_id", vendor.getId().toString()));
Logger.debug("Company has {} sessions", company.getSessionCount());
```

Returns:
```
[warn] 14:31:52.892 [play-dev-mode-akka.actor.default-dispatcher-49] - Error fetching payment contracts for vendor: 144
[debug] 14:31:53.141 [play-dev-mode-akka.actor.default-dispatcher-49] - api server response status[200] --
{"type":"company","company_id":"...","id":"...","app_id":"...","name":"...","remote_created_at": ...,"created_at": ...,"updated_at": ...,"last_request_at": ...,"monthly_spend": ...,"session_count": 758,"user_count": ...,"tags":{ ...},"segments":{...},"plan":{...},"custom_attributes":{...}}
-- 
[debug] 14:31:53.142 [play-dev-mode-akka.actor.default-dispatcher-49] - Company has 0 sessions
```

* * *

#### Steps to reproduce

1. Grab Company object from Java SDK.
2. Call getSessionCount() on company
3. Returns '0' every time

**Comment by thewheat** [comment]
Can confirm this is an issue.

Looks to be due to which overrides default behaviour and doesn't set the value

https://github.com/intercom/intercom-java/blob/fc9faa5d54c557d532305e24ee8e896af5566559/intercom-java/src/main/java/io/intercom/api/Company.java#L260-L271


The method will be removed in https://github.com/intercom/intercom-java/pull/183 so will wait for PR to be merged before we can close this
