### ISSUE TITLE
When updating User its updating all companies last seen time attached to User.

### ISSUE THREAD

**Issue by nikunjundhad** [intercom/intercom-java#205]
When we update user through java code like
**io.intercom.api.User.update(intercomUser);**
Its updating companies last seen time of all the companies attached with that user.

It leading to wrong name appear below user when we chatting with user on intercom inbox.
On inbox company name shown below userName is from the first company from right side companies and as we can see those companies list is shorted based on last updated time.

So its leading to wrong company name when we are chatting with user. It should only Update company last seen time when we are Updating Company not User.

## Version info
  - intercom-java version: 2.2.12
  - Java version: 1.8.0_171

## Expected behavior
  It should update company last seen time when we update company not when we update user.

## Actual behavior
  Its updating all the companies last seen time attached with user. Its leading to wrong last seen for the company.

## Steps to reproduce
 1. Add companies to user object
 2. Update User
 3. And you can see all the companies last seen time get updated.

**Comment by nikunjundhad** [comment]
I am updating user using **`io.intercom.api.User.update(intercomUser);`** and its updating last seen time of all the companies attached with him.
![snip20180706_3](https://user-images.githubusercontent.com/6352382/42392952-46b3f474-8172-11e8-9420-28ae4c37e107.png)

**Comment by thewheat** [comment]
Hi @nikunjundhad thanks for reporting this. I ran a couple of tests and I can confirm the behaviour you're seeing and looking into this further, looks like we update the last seen time on a company if it is included in the API call to the server
- e.g. if a user is associated to 5 companies but the update call includes the details on 1 company in the request (as shown below), it will update the "Last seen" time on that one company to the last seen time of the user
![image](https://user-images.githubusercontent.com/892961/42426206-a3e2dbb4-8358-11e8-919a-818c12219b33.png)

In the backend logs 
- if you do a `user = User.find` followed by a `User.update(user)` the update call actually includes **all companies associated to the user** 
- thus the example below will update the Company Last Seen time on all companies associated to the user
```
        Map<String, String> params = new HashMap<String, String>();
        params.put("user_id", "1");
        User user = User.find(params);
        user.setName("Name Java 1");
        User.update(user);
```

Moving on from this, I'll get in touch with the team on our end to see if updating the company last seen time is expected behaviour as I don't see being documented in our [API docs](https://developers.intercom.io/reference) but there is also some possible workarounds that you can use on your end 👍 

**Workaround 1**
Remove the company collection from the object so it isn't included in the update call
```
        User user = User.find(params);
        user.setName("Name from Java");
        user.setCompanyCollection(null);
        User.update(user);
```

**Workaround 2**
Instead of reusing the user object that comes from `.find`, create a new user object with just the data that you want to update. So long as you do not include companies in the new user, it will not update that user
```
        User user = new User();
        user.setUserId("1");
        user.setName("Name from Java");
        User.create(user);
```

**Comment by thewheat** [comment]
Got confirmation from the team that the "Company last seen" does update when you make an API request to the User Endpoint with the company information in the request itself.

So to prevent "Company last seen" from updating in your case would be to utilise either one of the workarounds suggested 👍 

We'll try update the docs to include a section regarding updating Company last seen time similar to the [User section on updating last seen time](https://developers.intercom.com/reference#updating-the-last-seen-time)

**Comment by nikunjundhad** [comment]
@thewheat I tried **Workaround 1** and problem with that is, i am not able to add one company after setting companyCollection to null.
        
        User user = User.find(params);
        user.setName("Name from Java");
        user.setCompanyCollection(null);
        user.addCompany(company);
        User.update(user);

This will throw exception because first we set companyCollection to null and then we added one company.
So can you please let me know how can i update only one company last seen time.

**Comment by thewheat** [comment]
If you need to add a company then you can set the company collection to a new collection and then add the company to it 👍 
```
    user.setCompanyCollection(new CompanyCollection());
    user.addCompany(company);
```
