### ISSUE TITLE
The method setUser(Contact) is undefined for the type ContactMessage

### ISSUE THREAD

**Issue by ryanagler** [intercom/intercom-java#209]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version:2.4.0
  - Java version:1.8

## Expected behavior
In the Usage section of this repository, it shows the code:
ContactMessage contactMessage = new ContactMessage()
    .setBody("Hey! Is there, is there a reward?")
    .setUser(contact);

Expected behavior is that passing a contact to setUser would work
## Actual behavior

The method setUser(Contact) is undefined for the type ContactMessage

## Steps to reproduce
 1. try calling new ContactMessage().setUser(contact)

**Comment by thewheat** [comment]
Hi @ryanagler looking at the code looks like the correct syntax is `.setFrom` not `.setUser`. 

![image](https://user-images.githubusercontent.com/892961/42949507-795edc4a-8ba4-11e8-9051-ea4656903d50.png)

I take it you got that sample code from the Readme? 

![image](https://user-images.githubusercontent.com/892961/42949665-da483b50-8ba4-11e8-84a0-9699d1b10359.png)

In fact there is a `.setUser` on a UserMessage but it has been [deprecated in this merge](https://github.com/intercom/intercom-java/commit/7f3b37fabfc9f9283c3b92a2576a0ad9e5bb756e) which introduced the `.setFrom` method

But moving on from this: we should update the readme to include the correct code. Happy for you to create a PR for it if you're up to it 😄  Otherwise I can get on to it next week 👍

**Comment by thewheat** [comment]
PR opened here https://github.com/intercom/intercom-java/pull/210
