### ISSUE TITLE
Intercom-java throwing "Illegal character(s) in message header value" error

### ISSUE THREAD

**Issue by Schwarzglut** [intercom/intercom-java#218]
A customer is receive the error from the title:
"Illegal character(s) in message header value: Basic"
When attempting to use the "find" functionality for a user with a specific User ID or email address.
Have confirmed the user exists and that they've set their token registration up correctly.

I found another conversation where a customer was also experiencing this issue but the customer stopped responding so there was no resolution.

## Version info
  - intercom-java version: 2.4.0

## Expected behavior

The user is returned when called.

## Actual behavior

An error message of 
"Illegal character(s) in message header value: Basic" 
is being returned instead.

## Steps to reproduce
 1. Set up code to find user
 2. Attempt to find user by User ID or email
 3. See the error message returned from the attmpted call

**Comment by thewheat** [comment]
Ran the following using 2.4.0 and it works as expected without any error
```
        Intercom.setToken(TOKEN);
        Map<String, String> params = Maps.newHashMap();
        params.put("user_id", "1");
        User user = User.find(params);
        System.out.println(user.getId());
```
![image](https://user-images.githubusercontent.com/892961/43889742-90c83e18-9bf7-11e8-94b8-c3bf83b02998.png)

Looking at the error message it seems that this has happened before due to old dependencies https://github.com/intercom/intercom-java/issues/3

Other possibilities that I could think of is if there could be some weird encoding of text that may cause weird corruption / output

So going to close this for now until we can get a reliable way to replicate this 👍
