### ISSUE TITLE
User.setLastRequestAt doesn't reflect in app

### ISSUE THREAD

**Issue by luposlip** [intercom/intercom-java#22]
Hey!

We have created a bunch of users in intercom. We want to update the lastRequestAt attribute to be able to see when they've logged on last (using intercom-java 1.0.0).

According to the API doc we should do this by using the user.setLastRequestAt setter. Here is the doc:
http://doc.intercom.io/api/#updating-the-last-seen-time

1: we find the user
2: we call user.setLastRequestAt(long)
3: we set user.setUpdateLastRequestAt(true) ; we've tried without this as well
4: we call User.update(user)

But no matter what we do, the "Last Seen" attribute on the user in the intercom app always seem to be updated to "now", meaning the time of the update via API.

Please advice!

Thanks in advance.

Best,
Henrik

![image](https://cloud.githubusercontent.com/assets/763627/4869963/8fd8aefe-6157-11e4-9f36-53c2963cf12c.png)

**Comment by luposlip** [comment]
Can this be closed with 1.0.4? Or in other words, does it work now?

**Comment by dehora** [comment]
@luposlip I'd expect this to work for you on any 1.x version - I've tried successfully on v1.0.0 and the current v1.1.1 release. I'm wondering if the `setLastRequestAt` was being set with milliseconds instead of seconds,eg using `System.currentTimeMillis` - a millisecond value will show up as `Just now`.
