### ISSUE TITLE
Conversation API not returning fields like channel, inbound_outbound, etc.

### ISSUE THREAD

**Issue by DaCodeShogun** [intercom/intercom-java#273]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version:
  - Java version:

## Expected behavior
Conversation object returns all the fields (same as the CSV exports from Intercom console)

## Actual behavior
Conversation object (from Conversation.list()) does not contain all the fields, such as `channel`, `inbound_outbound` etc.

## Steps to reproduce
 1. See above
 2. 
 3.

**Comment by lloydliyu** [comment]
Hey @DaCodeShogun :wave:

It is currently expected that the CSV export and the API output are different. If you haven't already, I'd recommend reaching out to the support team using the messenger on https://intercom.com to log this as a feature request. Version 2.0 does look to add more details to the conversation model, but this isn't compatible with the Java SDK at this time, and there may still be some disparity.

Closing this out as it is a limitation of the API rather than an issue with the SDK itself.
