### ISSUE TITLE
NotFoundException user not found when creating a user

### ISSUE THREAD

**Issue by LadyAiss** [intercom/intercom-java#281]
Hello,

A `NotFoundException` is sometimes thrown when creating a new intercom user. Could you please help me find out what causes it? 

It may be unrelated but I have read in the last API version documentation that the user model is being replaced with contacts : https://developers.intercom.com/intercom-api-reference/reference#users

Thanks in advance for the help.

## Version info
  - intercom-java version: 2.8.1
  - Java version: 13

## Expected behavior
Api creates new user

## Actual behavior
user creation fails and a `NotFoundException` is thrown

## Steps to reproduce
1. 
```
User intercomUser = new User();
     //add user information
```

 2. `User.create(intercomUser)`

## Logs
```
NotFoundException
User Not Found
io.intercom.api.HttpClient in throwException at line 207
io.intercom.api.HttpClient in handleError at line 169
io.intercom.api.HttpClient in runRequest at line 155
io.intercom.api.HttpClient in executeHttpMethod at line 110
io.intercom.api.HttpClient in post at line 100
io.intercom.api.DataResource in create at line 25
io.intercom.api.User in create at line 50
```

**Comment by lloydliyu** [comment]
Hey @LadyAiss :wave:

It looks like this issue is occurring with the API rather than directly with the SDK. If you're still running into this issue and you haven't already, I'd recommend reaching out to the support team using the messenger at https://intercom.com

From my experience issues like this are usually related to using the wrong version of the API (currently the Java SDK only supports versions 1.0 - 1.4 of the Intercom REST API) or from a race condition - but the support team will be able to dig further into this for you.

Closing this out as it is more related to the API than the SDK.
