### ISSUE TITLE
Create Company doesn't work

### ISSUE THREAD

**Issue by luposlip** [intercom/intercom-java#7]
I call the API using these lines:
    Company company = new Company();
        company.setName("Blue Sun");
        company.setCompanyID("1");
        company.setPlan(new Company.Plan("premium"));
        company.addCustomAttribute(CustomAttribute.newIntegerAttribute("foddstuff-items", 246));
        company.addCustomAttribute(CustomAttribute.newStringAttribute("bestseller", "fruity oaty bar"));
        Company.create(company);

I get the company back with this:
        HashMap<String, String> map = new HashMap<String, String>();
        map.put("name", "Blue Sun");
        Company company2 = Company.find(map);

And it seems fine. But no company is created in my intercom account.
And no exception is thrown.

Please advice?

**Comment by bledari** [comment]
Hi I have some issues.
I was trying to create companies through Postman and it didn't work, then with curl code it worked! I can retrieve companies by id and understand the list of companies displays only those with user. Now users I see are contacts. I was able to associate a contact to a company (difficult because doc has error, mark it as a POST) but still nothing in list companies.

You can try to reproduce this or just pass me some working Postman collection and I figure out why
